### ISSUE TITLE
About the saliency maps

### ISSUE THREAD

**Issue by wuzhenyubuaa** [NUST-Machine-Intelligence-Laboratory/nsrom#4]
The pre-computed saliency map how to obtain? ( not means how to obtain download URL)

**Comment by Italy2006** [comment]
> The pre-computed saliency map how to obtain? ( not means how to obtain download URL)

I have the same question as you。I found that the saliency map they use comes from the OAA, but this library does not explain how they obtained it.

**Comment by ChunmengLiu1** [comment]
As far as I know, it is a task of Salient Object Detection(SOD). Maybe you can search this task SOD for more information.




---Original---
From: ***@***.***&gt;
Date: Mon, Nov 15, 2021 11:32 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [NUST-Machine-Intelligence-Laboratory/nsrom] About the saliency maps (Issue #4)




  
The pre-computed saliency map how to obtain? ( not means how to obtain download URL)
  
I have the same question as you。I found that the saliency map they use comes from the OAA, but this library does not explain how they obtained it.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chentao2016** [comment]
The project of OAA has answered the question. Please check this issue (https://github.com/PengtaoJiang/OAA/issues/5).
